services:
  - type: static
    name: react-frontend
    buildCommand: "npm install && npm run build"
    publishPath: "frontend/build"
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: "https://your-backend-service.onrender.com"
