services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn my_project.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
