# Generated by Django 4.2.20 on 2025-03-30 08:20

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=product.models.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.category'),
        ),
    ]
