# Generated by Django 4.2.20 on 2025-05-10 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(
                decimal_places=2, 
                max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='products', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
