# Generated by Django 3.2.4 on 2025-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
